local runner = require("config.runner")

vim.keymap.set("n", "<leader>rr", runner.run_current, { desc = "Run Current File" })
vim.keymap.set("n", "<leader>rR", runner.run_last, { desc = "Run Last" })
vim.keymap.set("n", "<leader>ra", runner.run_current_with_args, { desc = "Run Current with Args" })
vim.keymap.set("n", "<leader>rs", runner.stop, { desc = "Stop Running Program" })
vim.keymap.set("n", "<leader>rp", runner.run_project_command, { desc = "Run Project Command" })
vim.keymap.set("n", "<leader>rm", runner.run_python_module, { desc = "Run Python Module" })
vim.keymap.set("x", "<leader>rx", runner.run_python_selection, { desc = "Run Python Selection" })

vim.keymap.set("n", "<leader>mc", "<cmd>CMakeGenerate<cr>", { desc = "CMake Configure" })
vim.keymap.set("n", "<leader>mb", "<cmd>CMakeBuild<cr>", { desc = "CMake Build" })
vim.keymap.set("n", "<leader>mr", "<cmd>CMakeRun<cr>", { desc = "CMake Run Target" })
vim.keymap.set("n", "<leader>md", "<cmd>CMakeDebug<cr>", { desc = "CMake Debug Target" })
vim.keymap.set("n", "<leader>mt", "<cmd>CMakeSelectLaunchTarget<cr>", { desc = "CMake Select Target" })
vim.keymap.set("n", "<leader>mp", "<cmd>CMakeSelectConfigurePreset<cr>", { desc = "CMake Select Preset" })
vim.keymap.set("n", "<leader>my", "<cmd>CMakeSelectBuildType<cr>", { desc = "CMake Select Build Type" })

vim.keymap.set("n", "<leader>cb", runner.build_current, { desc = "Build Current File/Project" })
vim.keymap.set("n", "<leader>df", runner.debug_current, { desc = "Debug Current File" })
vim.keymap.set("n", "<leader>dL", function()
  require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, { desc = "Set Log Point" })
vim.keymap.set("n", "<leader>dR", function()
  require("dap").restart()
end, { desc = "Restart Debug Session" })
